apiVersion: v1
kind: Service
metadata:
  name: ecommerce-microservices
spec:
  type: NodePort
  selector:
    app: ecommerce-microservices
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
