version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxODk5OTAxNCwiaWF0IjoxNzE4OTk5MDE0fQ.fuJ4W_DfEEuneMLEdFX5dh0apO4mcgK4O6B8l-gMvuI
      - MONGO_URI=mongodb+srv://ashishprabhu2143:ashishprabhu2143@cluster0.plbfgel.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - '3000:3000'
