version: '3'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  server:
    build: server
    environment:
      - PORT=5000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:3000
      - JWT_SECRET=update_your_JWT_secret
      - MONGO_URI=update_your_mongo_URI
    ports:
      - '3000:3000'
